import { Navbar } from "@/components/shared/navbar";
import { Footer } from "@/components/shared/footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f9fafb]">
      <Navbar />
      <main className="pt-24 pb-16 mx-auto max-w-3xl px-4">
        <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-gray-400">Last updated: May 2026</p>
        <div className="mt-8 prose prose-sm text-gray-600 space-y-4">
          <h2 className="text-lg font-bold text-gray-900">1. Service Description</h2>
          <p>EyeGuard is an AI-powered eye health monitoring tool designed for educational and wellness purposes. It is <strong>not a medical device</strong> and should not replace professional eye care.</p>
          <h2 className="text-lg font-bold text-gray-900">2. No Medical Advice</h2>
          <p>The fatigue scores, health assessments, and chatbot responses are generated by AI and are for informational purposes only. Always consult a qualified ophthalmologist for eye health concerns.</p>
          <h2 className="text-lg font-bold text-gray-900">3. Camera Access</h2>
          <p>EyeGuard requires webcam access for eye tracking. Video is processed entirely in your browser and is never recorded or transmitted.</p>
          <h2 className="text-lg font-bold text-gray-900">4. Accuracy</h2>
          <p>While we use state-of-the-art MediaPipe face landmarks for blink detection, results may vary based on lighting, camera quality, and positioning.</p>
          <h2 className="text-lg font-bold text-gray-900">5. Limitation of Liability</h2>
          <p>EyeGuard is provided "as is" without warranty. We are not liable for any health decisions made based on the app's output.</p>
          <h2 className="text-lg font-bold text-gray-900">6. Contact</h2>
          <p>For questions, reach us at <a href="mailto:gauravkumarmehta100@gmail.com" className="text-[#5B6CFF]">gauravkumarmehta100@gmail.com</a></p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
